estudiolapa/estudiolapa/urls.py
from django.contrib import admin
from django.urls import path
from home.views import home
# import home, blog

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    # path('blog/', blog.urls),
]

estudiolapa/blog/models.py
from django.db import models

# Create your models here.

estudiolapa/home/models.py
import logging
from django.db import models
from django.utils.text import slugify
from thumbnails import get_thumbnail


logger = logging.getLogger(__name__)


class _BaseModel(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(null=True, blank=True)
    THUMBNAIL_SPECS = ()

    @property
    def slug(self):
        return slugify(self.title)

    def _get_thumbnail(self, size="200x200", crop="center"):
        if self.image:
            try:
                return get_thumbnail(self.image.file.name, size, crop=crop)
            except Exception as e:
                logger.error(e)

    @property
    def resized_image(self):
        return self._get_thumbnail(*self.THUMBNAIL_SPECS)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True


BACKGROUND_PLACES = (
    ('bg_logo', 'Fundo da Logo'),
    ('bg_fazemos', 'Fundo do O que fazemos?'),
)
class Background(_BaseModel):

    title = models.CharField(max_length=255, verbose_name=u'Título')
    place = models.CharField(max_length=20, choices=BACKGROUND_PLACES,
                             verbose_name='Local', default='BG Logo')
    THUMBNAIL_SPECS = ("1920x1275", "center")

    class Meta:
        verbose_name = 'Plano de Fundo'
        verbose_name_plural = 'Planos de Fundo'
        get_latest_by = 'updated_at'


class Category(_BaseModel):

    title = models.CharField(max_length=255, verbose_name=u'Título')
    description = models.TextField(null=True, blank=True, verbose_name=u'Descrição')
    THUMBNAIL_SPECS = ("750x500", "center")

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'


class CategoryPhoto(_BaseModel):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name=u'Título')
    THUMBNAIL_SPECS = ("80x80", "center")

    @property
    def slide_image(self):
        return self._get_thumbnail("1024", None)

    class Meta:
        verbose_name = 'Foto de Categoria'
        verbose_name_plural = 'Fotos de Categorias'


class Work(_BaseModel):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name=u'Título')
    description = models.TextField(null=True, blank=True, verbose_name=u'Descrição')
    youtube_url = models.CharField(max_length=255, null=True, blank=True)
    vimeo_url = models.CharField(max_length=255, null=True, blank=True)
    THUMBNAIL_SPECS = ("750x500", "center")

    class Meta:
        verbose_name = 'Trabalho Realizado'
        verbose_name_plural = 'Trabalhos Realizados'


class WorkPhoto(_BaseModel):

    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name=u'Título')
    THUMBNAIL_SPECS = ("80x80", "center")

    @property
    def slide_image(self):
        return self._get_thumbnail("1024", None)

    class Meta:
        verbose_name = 'Foto de Trabalho Realizado'
        verbose_name_plural = 'Fotos de Trabalhos Realizados'

estudiolapa/blog/views.py
from django.shortcuts import render

# Create your views here.

estudiolapa/home/views.py
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from home import models


def get_backgrounds():
    result = {}
    for place in models.BACKGROUND_PLACES:
        try:
            p = models.Background.objects.filter(place=place[0]).latest()
        except:
            pass
        else:
            result.update({
                place[0]: p.resized_image.url
            })
    return result

def send_contact_email(request):
    send_mail(
        '[Contato do EstudioLapa.com] - Mensagem de %(name)s' % request.POST,
        u'''
        Olá,

        Alguém enviou uma mensagem através do site:

        Remetente: %(name)s

        Email: %(email)s

        Mensagem: %(message)s

        Att,
        Adminstrador
        ''' % request.POST, settings.EMAIL_HOST_USER,
        ['contato@estudiolapa.com'], fail_silently=False
    )
    messages.success(request, 'E-mail de contanto enviado com sucesso.')


def home(request):
    context = {
        'categories': models.Category.objects.all(),
        'works': models.Work.objects.order_by('-updated_at'),
        'backgrounds': get_backgrounds()
    }

    if request.method == 'POST':
        send_contact_email(request)

    return render(request, 'home.html', context)

estudiolapa/home/templates/about.html
<div class="section clearfix object-non-visible" data-animation-effect="fadeIn">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 id="about" class="title text-center">Quem <span>Somos?</span></h1>
                <p class="lead text-center">Somos um time apaixonado de fotográfos, artistas e cinegrafistas.</p>
                <div class="space"></div>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li><i class="fa fa-caret-right pr-10 text-colored"></i> Fotografia de eventos</li>
                            <li><i class="fa fa-caret-right pr-10 text-colored"></i> Produção completa de casamentos</li>
                            <li><i class="fa fa-caret-right pr-10 text-colored"></i> Books fotográficos</li>
                            <li><i class="fa fa-caret-right pr-10 text-colored"></i> Eventos de moda</li>
                            <li><i class="fa fa-caret-right pr-10 text-colored"></i> Drones aéreos</li>
                            <li><i class="fa fa-caret-right pr-10 text-colored"></i> Fotos e vídeos 360</li>
                            <li><i class="fa fa-caret-right pr-10 text-colored"></i> Tour Virtual</li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <p>Nosso sonho é eternizar cada clique. Cada frame de nossas máquinas.</p>
                        <p>Entedemos a importância de nosso papel na realização de seu sonho</p>
                        <p>O universo consipira a nosso favor.</p>
                        <p>A vida é feita de detalhes!</p>
                        <p>E é isso que nos interessa</p>
                        <p>Somos movidos pela emoção e trabalhamos com o que mais amamos! Pessoas e imagens.</p>
                        <p>Seja qual for o lugar ou situação, nos convide. Estaremos lá.</p>
                        <p><strong>Conte conosco!</strong></p>
                    </div>
                </div>
                <div class="space"></div>
            </div>
        </div>
    </div>
</div>

estudiolapa/home/templates/banner.html
<!-- banner start -->
<!-- ================ -->
<div id="banner" class="banner">
    <div class="banner-image" data-image="{{ backgrounds.bg_logo }}"></div>
    <div class="banner-caption">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 object-non-visible" data-animation-effect="fadeIn">
                    <img class="text-center" src="/static/images/Azul_Vertical.png" style="width: 40%; margin-left: 30%;" />
                </div>
            </div>
        </div>
    </div>
</div>
<!-- banner end -->

estudiolapa/home/templates/categories.html
<div class="section translucent-bg pb-clear categories" style="background-image: url({{ backgrounds.bg_fazemos }})">
    <div class="container object-non-visible" data-animation-effect="fadeIn">
        <h1 id="services" class="title text-center">O que <span>fazemos?</span></h1>
        <div class="space"></div>
        <div class="row">
        {% for category in categories %}
        <div class="col-md-4" {% cycle 'style="clear:both;"' '' '' %}>
            <div class="media testimonial">
                <div class="media-body">
                    <h3 class="media-heading">{{ category.title }}</h3>
                    <div class="isotope-item web-design">
                        <div class="image-box">
                            <div class="overlay-container">
                                <img src="{{ category.resized_image.url }}" alt="">
                                <a class="overlay" data-toggle="modal" data-target="#category-{{ category.slug }}">
                                    <i class="fa fa-search-plus"></i>
                                    <span>{{ category.title }} - Clique pra detalhes</span>
                                </a>
                            </div>
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="category-{{ category.slug }}" tabindex="-1" role="dialog" aria-labelledby="category-{{ category.slug }}-label" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                        <h4 class="modal-title" id="category-{{ category.slug }}-label">{{ category.title }}</h4>
                                    </div>
                                    <div class="modal-body">
                                        <h3>{{ category.title }}</h3>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>{{ category.description }}</p>
                                                {% with category.categoryphoto_set.all as photos %}
                                                    {% include "photo_gallery.html" %}
                                                {% endwith %}
                                            </div>
                                            <div class="col-md-6">
                                                <img src="{{ category.resized_image.url }}" alt="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Fechar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Modal end -->
                    </div>
                    <p>{{ category.description|truncatewords:20 }}</p>
                </div>
            </div>
        </div>
        {% endfor%}
        </div>
        <div class="row">
        </div>
    </div>
</div>

estudiolapa/home/templates/footer.html
<footer id="footer">
    <div class="footer section">
        <div class="container">
            <h1 class="title text-center" id="contact">Contato</h1>
            <div class="space"></div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="footer-content">
                        <p class="large">Ligue-nos ou venha bater um papo com a gente!</p>
                        <ul class="list-icons">
                            <li><i class="fa fa-map-marker pr-10"></i> Rua Caratiá, 59 - BH / MG</li>
                            <li><i class="fa fa-phone pr-10"></i> (31) 9932-9819</li>
                            <li><i class="fa fa-envelope-o pr-10"></i> contato@estudiolapa.com</li>
                        </ul>
                        <ul class="social-links">
                            <li class="facebook"><a target="_blank" href="https://www.facebook.com/pages/HtmlCoder/714570988650168"><i class="fa fa-facebook"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="footer-content">
                        <form role="form" id="footer-form" action="/" method="POST">
                            {% csrf_token %}
                            <div class="form-group has-feedback">
                                <label class="sr-only" for="name">Nome</label>
                                <input type="text" class="form-control" id="name2" placeholder="Name" name="name" required>
                                <i class="fa fa-user form-control-feedback"></i>
                            </div>
                            <div class="form-group has-feedback">
                                <label class="sr-only" for="email">E-mail</label>
                                <input type="email" class="form-control" id="email2" placeholder="Enter email" name="email" required>
                                <i class="fa fa-envelope form-control-feedback"></i>
                            </div>
                            <div class="form-group has-feedback">
                                <label class="sr-only" for="message">Mensagem</label>
                                <textarea class="form-control" rows="8" id="message2" placeholder="Message" name="message" required></textarea>
                                <i class="fa fa-pencil form-control-feedback"></i>
                            </div>
                            <input type="submit" value="Enviar" class="btn btn-default">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="subfooter">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center">© 2015 Estúdio Lapa.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

estudiolapa/home/templates/gallery.html
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery  blueimp-gallery-controls" data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

estudiolapa/home/templates/header.html
<header class="header fixed clearfix navbar navbar-fixed-top">
    <div class="container">
        <div class="row">
            <div class="col-md-4">

                <!-- header-left start -->
                <!-- ================ -->
                <div class="header-left clearfix">

                    <!-- logo -->
                    <div class="logo smooth-scroll">
                        <a href="#banner"><img id="logo" src="/static/images/Azul_Horizontal.png" alt="Worthy" style="width: 200px;"></a>
                    </div>
                    <!-- logo end -->

                </div>
                <!-- header-left end -->

            </div>
            <div class="col-md-8">

                <!-- header-right start -->
                <!-- ================ -->
                <div class="header-right clearfix">

                    <!-- main-navigation start -->
                    <!-- ================ -->
                    <div class="main-navigation animated">

                        <!-- navbar start -->
                        <!-- ================ -->
                        <nav class="navbar navbar-default" role="navigation">
                            <div class="container-fluid">

                                <!-- Toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse scrollspy smooth-scroll" id="navbar-collapse-1">
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="active"><a href="#banner">Início</a></li>
                                        <li><a href="#about">Quem somos?</a></li>
                                        <li><a href="#services">O que fazemos</a></li>
                                        <li><a href="#portfolio">Trabalhos realizados</a></li>
                                        <li><a href="#contact">Contato</a></li>
                                    </ul>
                                </div>

                            </div>
                        </nav>
                        <!-- navbar end -->

                    </div>
                    <!-- main-navigation end -->

                </div>
                <!-- header-right end -->

            </div>
        </div>
    </div>
</header>

estudiolapa/home/templates/home.html
<!DOCTYPE html>
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title>Estúdio Lapa | Fotografia, Cinegrafia, Eventos, 360, Drones</title>
        <meta name="description" content="Estúdio Lapa | Fotografia, Cinegrafia, Eventos, 360, Drones">
        <meta name="author" content="ricardodani.com">
        <meta name="google-site-verification" content="tdmS6PthHLbGKXR9HZt08wCR8Zc_eWcrN87N0r-Q-cU" />
        <!-- Mobile Meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Favicon -->
        <link rel="shortcut icon" href="/static/images/favicon.ico">

        <!-- Web Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700,300&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Raleway:700,400,300' rel='stylesheet' type='text/css'>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

        <!-- Font Awesome CSS -->
        <link href="/static/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">

        <!-- Plugins -->
        <link href="/static/css/animations.css" rel="stylesheet">

        <!-- Worthy core CSS file -->
        <link href="/static/css/style.css" rel="stylesheet">

        <!-- Bootstrap Image Gallery -->
        <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
        <link rel="stylesheet" href="/static/css/bootstrap-image-gallery.min.css">
    </head>

    <body class="no-trans">
        <!-- scrollToTop -->
        <!-- ================ -->
        <div class="scrollToTop"><i class="icon-up-open-big"></i></div>
        {% include "gallery.html" %}
        {% include "header.html" %}
        {% include "banner.html" %}
        {% include "about.html" %}
        {% include "categories.html" %}
        {% include "works.html" %}
        {% include "phrase.html" %}
        {% include "footer.html" %}
        {% if messages %}
          <script >
          {% for message in messages %}
            alert("{{ message }}");
          {% endfor %}
          </script>
        {% endif %}
        <!-- JavaScript files placed at the end of the document so the pages load faster
        ================================================== -->
        <!-- Jquery and Bootstap core js files -->
        <script type="text/javascript" src="/static/plugins/jquery.min.js"></script>
        <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>

        <!-- Modernizr javascript -->
        <script type="text/javascript" src="/static/plugins/modernizr.js"></script>

        <!-- Isotope javascript -->
        <script type="text/javascript" src="/static/plugins/isotope/isotope.pkgd.min.js"></script>

        <!-- Backstretch javascript -->
        <script type="text/javascript" src="/static/plugins/jquery.backstretch.min.js"></script>

        <!-- Appear javascript -->
        <script type="text/javascript" src="/static/plugins/jquery.appear.js"></script>

        <!-- Initialization of Plugins -->
        <script type="text/javascript" src="/static/js/template.js"></script>

        <!-- Custom Scripts -->
        <script type="text/javascript" src="/static/js/custom.js"></script>

        <!-- Bootstrap Image Gallery -->
        <script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>

    </body>
</html>

estudiolapa/home/templates/photo_gallery.html
{% if photos %}
<h4>Ver galeria</h4>
<div id="gallery-{{ work.id }}" class="gallery">
    {% for photo in photos %}
    <a href="{{ photo.slide_image.url }}" title="{{ photo.title }}">
        <img src="{{ photo.resized_image.url }}" alt="{{ photo.title }}">
    </a>
    {% endfor %}
</div>
<script>
document.getElementById('gallery-{{ work.id }}').onclick = function (event) {
    event = event || window.event;
    var target = event.target || event.srcElement,
        link = target.src ? target.parentNode : target,
        options = {index: link, event: event},
        links = this.getElementsByTagName('a');
    blueimp.Gallery(links, options);
};
</script>
{% endif %}

estudiolapa/home/templates/phrase.html
<div class="default-bg space blue">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h1 class="text-center">Encaramos nosso trabalho como arte, e a arte como estilo de vida</h1>
            </div>
        </div>
    </div>
</div>

estudiolapa/home/templates/work.html
<div class="col-sm-6 col-md-3 isotope-item {{ work.category.slug }}">
    <div class="image-box">
        <div class="overlay-container">
            <img src="{{ work.resized_image.url }}" alt="">
            <a class="overlay" data-toggle="modal" data-target="#work-{{ work.slug }}">
                <i class="fa fa-search-plus"></i>
                <span>{{ work.category.title }}</span>
            </a>
        </div>
        <a class="btn btn-default btn-block" data-toggle="modal" data-target="#work-{{ work.slug }}">{{ work.title }}</a>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="work-{{ work.slug }}" tabindex="-1" role="dialog" aria-labelledby="project-1-label" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                    <h4 class="modal-title" id="project-1-label">{{ work.title }}</h4>
                </div>
                <div class="modal-body">
                    <h3>{{ work.title }}</h3>
                    <div class="row">
                        <div class="col-md-{% if work.youtube_url %}12{% else %}6{% endif %}">
                            <p>{{ work.description }}</p>
                            {% if work.youtube_url %}
                                <iframe width="860" height="515" src="{{ work.youtube_url }}" frameborder="0" allowfullscreen></iframe>
                            {% elif work.vimeo_url %}
                                <iframe src="{{ work.vimeo_url }}" width="860" height="515" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

                            {% else %}
                                {% with work.workphoto_set.all as photos %}
                                    {% include "photo_gallery.html" %}
                                {% endwith %}
                            {% endif %}
                        </div>
                        {% if not work.youtube_url  %}
                        {% if not work.vimeo_url  %}

                        <div class="col-md-6">
                            <img src="{{ work.resized_image.url }}" alt="">
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal end -->
</div>

estudiolapa/home/templates/works.html
<div class="section">

    <div class="container">
        <h1 id="portfolio" class="title text-center">Trabalhos <span>Realizados</span></h1>
        <div class="separator"></div>
        <p class="lead text-center">Um pouco do nosso trabalho, que é feito com muita dedicação e amor a arte e a fotografia.</p>
        <br>            
        <div class="row object-non-visible" data-animation-effect="fadeIn">
            <div class="col-md-12">

                <!-- isotope filters start -->
                <div class="filters text-center">
                    <ul class="nav nav-pills">
                        <li class="active"><a href="#" data-filter="*">Todos</a></li>
                        {% for category in categories %}
                        <li><a href="#" data-filter=".{{ category.slug }}">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- isotope filters end -->

                <!-- portfolio items start -->
                <div class="isotope-container row grid-space-20">
                    {% for work in works %}
                        {% include "work.html" %}
                    {% endfor %}
                </div>
                <!-- portfolio items end -->
            
            </div>
        </div>
    </div>
</div>